---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "README-"
)
```

# scerden.rentrez

Very small wrapper around `rentrez` R pkg from ropensci.

## install
```{r, eval = F}
devtools::install_github("scerden/scerden.rentrez")
```


Pkg makes avaiable 2 functions:  
1. `pubmed_search()` searches pubmed and returns a (character vector of) the matching db id(s).  
2. `pubmed_summary()` returns a tibble of useful variables, one row per input id.

## demo
```{r}
library(scerden.rentrez)
library(tidyverse)

"topoisomerase" %>% pubmed_search(retmax = 10)
"topoisomerase" %>% pubmed_search(retmax = 10, verbose = T) # troubleshooting
"topoisomerase" %>% pubmed_search(retmax = 10) %>% pubmed_summary()

series_ids <- c("GSE41494", "GSE68016", "GSE8305") # geo series ids for which you want to track down citing papers
res <- tibble(gse = series_ids, 
              pmid = map(gse, pubmed_search),
              psummary = map(pmid, pubmed_summary))
res
res %>% unnest()
```



## pkg creation:

* Prelims  
```{r, eval = F}
use_readme_rmd()
use_data_raw()
use_testthat()
```

* when writing `./R` fxns  
```{r, eval = F}
use_package("tibble")
use_package("rentrez")
use_package("dplyr")
use_package("purrr")
```
